version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges